#!/bin/bash

#PBS -l select=1:ncpus=22:mpiprocs=1:ngpus=1

#PBS -A ERDCV00898ERS

#PBS -l walltime=8:00:00

#PBS -q standard

#PBS -N clean_data

#PBS -m be
#PBS -M joseph.e.jabour@erdc.dren.mil

## Execution block

cd ${HOME}

source .bashrc

cd ${WORKDIR}/AI_NLP/PDFs/

SYS_PYTHON=$(which python)

conda activate algorithms

python -m spacy download en_core_web_sm

python nltk-test.py

python spacy-test.py

